Repository globe-and-citizen/Celebrity-Fanalyzer, pull requests merged in 2022-11, with the labels that each got.

#4 feat: Create skeleton model for article
  src/components/ArticleSkeleton.vue
  src/pages/SearchPage.vue
Labels: enhancement, good first issue

#10 feat: add editor config rules and format code using prettier
  .editorconfig
  .eslintrc.js
  index.html
  src-pwa/custom-service-worker.js
  src-pwa/register-service-worker.js
Labels: enhancement

#15 docs: Updating the Standard Trio of docs
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  README.md
Labels: documentation
