Repository globe-and-citizen/Celebrity-Fanalyzer, pull requests merged in 2024-09, with the labels that each got.

#512 Feature/common prompt entry advertisement create button in header 499
  firestore.indexs.json
  src/components/Admin/PromptCard.vue
  src/components/Advertiser/AdvertiserTable.vue
  src/components/shared/TheHeader.vue
  src/pages/admin/AdminIndex.vue
  src/stores/advertises.js
  src/stores/prompts.js
Labels: enhancement, General Suggestion

#540 Enhancement:While creating prompt,entry,advertisement mandatory field should be mentioned.
  src/components/Admin/EntryCard.vue
  src/components/Admin/PromptCard.vue
  src/components/Advertiser/AdvertiseCard.vue
Labels: enhancement, General Suggestion

#545 fix:#544 fixed failing vitest tests
  src/components/Profile/SettingsTab.vue
  src/stores/__tests__/visitor.spec.js
  src/stores/prompts.js
  src/stores/user.js
  src/stores/visitors.js
Labels: bug, performance

#547 fix:#541 Fix image resizing, so tall images are correctly handled
  src/pages/IndexPage.vue
  src/utils/imageConvertor.js
Labels: bug, intermediate, General Suggestion

#554 comments-sorting-fixed
  firestore.indexs.json
  src/stores/comments.js
Labels: bug

#560 feat:#534 implemented loading skeleton cards to be a specific number and responsie to UI
  src/components/shared/ArticleSkeleton.vue
  src/pages/SearchPage.vue
Labels: enhancement, General Suggestion

#561 Improvement/manage prompts & entries filter data 546
  src/components/Admin/ManagePromptsEntries.vue
Labels: enhancement, General Suggestion

#571 fixes #569 default prompt and entries instead of ads
  src/layouts/MainMenu.vue
Labels: bug

#572 fix:#567 fix for entry not editable
  src/components/Admin/EntryCard.vue
Labels: bug

#549 Enhancement:save crypto wallet address 533
  src/components/Profile/ProfileTab.vue
  src/components/Profile/Web3ModalComponent.vue
Labels: enhancement, General Suggestion

#578 565 add clickable links for entry title and author name
  src/components/Admin/ManagePromptsEntries.vue
  src/components/Admin/TableEntry.vue
  src/css/app.css
Labels: enhancement, General Suggestion

#562 feat:#502 Improved immediate ui feedback for likes and dislikes
  src/components/Posts/ThePost.vue
  src/stores/likes.js
Labels: bug, enhancement, General Suggestion

#582 profile picture field improved
  src/components/Profile/ProfileTab.vue
Labels: enhancement, General Suggestion

#590 feat:#589 - set minimum budget for ad to 3 usd
  src/components/Advertiser/AdvertiseCard.vue
Labels: bug, enhancement, General Suggestion

#583 Enhancement/username field copy button 551
  src/components/Profile/LoginForm.vue
  src/components/Profile/ProfileTab.vue
  src/stores/user.js
Labels: bug, enhancement, General Suggestion

#563 feat:#548 added escrow id for entries on writers admin panel
  src/components/Admin/EntryCard.vue
  src/stores/entries.js
Labels: enhancement, General Suggestion

#591 FEAT/#570 Sharing the Entry or Prompt You Just Created
  src/components/Admin/ManagePromptsEntries.vue
  src/components/Admin/TableEntry.vue
  src/components/Posts/ShareComponent.vue
Labels: enhancement, General Suggestion

#598 fix:#597 - removed google tag manager and tracking
  index.html
Labels: bug, General Suggestion

#587 Bugfix/restrict entry name same prompt 573
  src/components/Admin/EntryCard.vue
  src/stores/entries.js
Labels: bug, General Suggestion

#564 Feature/484 funding prompt flow
  .env
  .gitignore
  src/components/Admin/CryptoTransactionDetailCard.vue
  src/components/Admin/FundDepositCard.vue
  src/components/Admin/ManagePromptsEntries.vue
  src/components/Admin/TableEntry.vue
  src/components/Admin/WalletPaymentCard.vue
  src/components/Advertiser/AdvertiserTable.vue
  src/contracts/artifacts/contracts/CompetitionEscrow.sol/CompetitionEscrow.dbg.json
  src/contracts/artifacts/contracts/CompetitionEscrow.sol/CompetitionEscrow.json
  src/stores/prompts.js
  src/web3/adCampaignManager.js
  src/web3/escrow.js
  src/web3/transfers.js
Labels: enhancement, advanced, General Suggestion

#496 Enhancement/lazy loading for prompts on the search page 463
  src/layouts/MainMenu.vue
  src/pages/SearchPage.vue
  src/stores/prompts.js
Labels: General Suggestion

#579 feat:#555 Implemented install celebrity fanalyzer banner
  favicon.ico
  package-lock.json
  package.json
  public/screenshot.png
  public/screenshot2.png
  public/site.webmanifest
  quasar.config.js
  src-pwa/manifest.json
  src/components/shared/InstallAppBanner.vue
  src/layouts/MainMenu.vue
Labels: enhancement, General Suggestion

#602 fix:#601 - fix error for creating ads. Ads cost not updating fix
  src/components/Advertiser/AdvertiseCard.vue
  src/components/Advertiser/AdvertiserTable.vue
  src/web3/adCampaignManager.js
Labels: bug

#596 feat:#586 - Removed unnecessary ad validation
  src/stores/advertises.js
Labels: bug

#599 fix:#575, #600 - duplicate comment if hitting enter multiple times & Restricted Only Spaces or Empty
  src/components/Posts/TheComments.vue
Labels: bug, General Suggestion
