Repository globe-and-citizen/Celebrity-Fanalyzer, pull requests merged in 2024-11, with the labels that each got.

#634 fix:#633 - Cypress tests fixes
  src/components/Posts/TheComments.vue
  src/components/shared/TheHeader.vue
  src/stores/comments.js
  src/stores/prompts.js
  test/cypress/e2e/admin-prompt-entry.cy.js
  test/cypress/e2e/permissions.cy.js
Labels: General Suggestion

#655 feat:#636 - implemented profile picture upload dialog
  src/components/Profile/ProfileTab.vue
Labels: enhancement, General Suggestion

#663 fix:#662 - Fixed advertisement status incorrectly show budget crossed
  functions/index.js
Labels: bug, General Suggestion

#659 fix:#658 - Fix load more button after filtering
  src/components/Admin/ManagePromptsEntries.vue
  src/pages/SearchPage.vue
  test/cypress/e2e/admin-prompt-entry.cy.js
Labels: bug, General Suggestion

#661 fix:#660 - Fixed main menu admin table remain active
  src/pages/admin/AdminIndex.vue
Labels: bug, General Suggestion
