Repository globe-and-citizen/Celebrity-Fanalyzer, pull requests merged in 2024-08, with the labels that each got.

#464 fix/Deleted entry still shown on prompt page #458
  src/stores/entries.js
Labels: bug

#462 Fixed: Formatting for Advertisement Blurbs
  src/components/Advertiser/AdvertiseCard.vue
  src/components/Advertiser/AdvertiserTable.vue
  src/components/Advertiser/CampaignCard.vue
  src/components/Posts/ThePost.vue
Labels: enhancement

#466 added login redirection for unauthenticated users while clicking to create entry button.
  src/components/shared/TheEntries.vue
Labels: bug, enhancement, General Suggestion

#467 Minor changes on the Header Title and subtitle view.
  src/components/shared/TheHeader.vue
Labels: enhancement, General Suggestion

#461 Fixed: Progress / "Loading Wheel" to Display During Navigation
  src/components/shared/LoadingSpinner.vue
  src/layouts/MainLayout.vue
  src/router/index.js
  src/stores/index.js
  src/stores/loading.js
Labels: good first issue, General Suggestion

#473 Organize entries by created #470
  src/components/Admin/ManagePromptsEntries.vue
  src/components/Admin/TableEntry.vue
  src/components/Advertiser/AdvertiserTable.vue
  src/stores/entries.js
Labels: bug, General Suggestion

#475 Fixed no prompt available for selection #474
  src/components/Admin/EntryCard.vue
Labels: bug

#477 Visible indications for users to know the image is required #476
  src/components/Admin/EntryCard.vue
Labels: enhancement, good first issue, General Suggestion

#488 Enhancement/forgot password button 472
  src/components/Profile/LoginForm.vue
  src/firebase.js
Labels: enhancement, General Suggestion

#487 Issue/make the entry editable 471
  src/components/Admin/EntryCard.vue
  src/components/Posts/ThePost.vue
  src/pages/EntryPage.vue
Labels: enhancement, General Suggestion

#489 enhancement:skeleton-comments-during-loading-482
  src/components/Posts/TheComments.vue
  src/components/shared/CommentsSkeleton.vue
  src/stores/comments.js
Labels: enhancement, General Suggestion

#492 Fix issue with 404 error
  .env
  src/components/Posts/ThePost.vue
  src/pages/CampaignPage.vue
  src/pages/EntryPage.vue
  src/pages/PromptPage.vue
  src/stores/advertises.js
  src/stores/entries.js
  src/stores/prompts.js
  src/stores/stats.js
  src/utils/activityTracker.js
  src/utils/layer8Init.js
Labels: enhancement, advanced

#495 enhancement:optimize-ad-fetching-on-campaign-page
  src/pages/CampaignPage.vue
  src/stores/advertises.js
Labels: enhancement, General Suggestion, performance

#500 Fix for prompts url edge cases
  src/components/Admin/PromptCard.vue
Labels: bug, good first issue, General Suggestion

#501 Fix for stats graph to be displayed properly
  src/components/Posts/Graphs/HalfDonought.vue
  src/components/Posts/Graphs/PieChart.vue
  src/components/Posts/Graphs/PopularityGauge.vue
  src/components/Posts/Graphs/UserRatingGauge.vue
  src/components/Posts/Graphs/us-states.json
  src/components/Posts/TheAnthrogram.vue
  src/components/Posts/ThePost.vue
  src/stores/stats.js
Labels: bug

#494 User can directly Edit the advertisement and prompt from the same page.
  src/components/Admin/PromptCard.vue
  src/components/Advertiser/AdvertiserTable.vue
  src/components/Posts/ThePost.vue
  src/pages/CampaignPage.vue
  src/pages/EntryPage.vue
  src/pages/PromptPage.vue
  src/stores/advertises.js
  src/stores/prompts.js
  src/utils/date.js
Labels: enhancement, General Suggestion

#503 Fix for not showing available prompt for entries in some cases
  src/components/Admin/EntryCard.vue
  src/components/Posts/TheAnthrogram.vue
Labels: bug

#514 Fixed: When Editing Your Own Prompt, You Need Another Title #506
  src/components/Admin/PromptCard.vue
Labels: bug, enhancement, General Suggestion

#513 Enhancement: Email Sign Up Regex Check
  src/components/Profile/LoginForm.vue
Labels: bug, enhancement, General Suggestion

#511 Enhancement/a same user can create a single entry for the single prompt 498
  src/components/Admin/EntryCard.vue
  src/components/shared/TheEntries.vue
  src/stores/entries.js
Labels: enhancement, General Suggestion

#527 Fixed: Like/Dislike button in advertisement is not working.
  src/components/Posts/ThePost.vue
Labels: bug, enhancement, General Suggestion

#529 Fixed: Clicking on the subscribe button in Prompt's page is not changing the subscribe count instantly.
  src/stores/notifications.js
Labels: bug, enhancement, General Suggestion

#524 Tanstack setup. Removed layer8. Added layer8 mock. Service worker
  .env
  package-lock.json
  package.json
  quasar.config.js
  src-pwa/custom-service-worker.js
  src-pwa/manifest.json
  src/App.vue
  src/boot/tanstack-query.js
  src/components/Posts/ThePost.vue
  src/components/shared/ItemCard.vue
  src/pages/IndexPage.vue
  src/stores/comments.js
  src/stores/likes.js
  src/stores/shares.js
  src/stores/stats.js
  src/stores/user.js
  src/utils/layer8Init.js
Labels: enhancement, advanced, performance

#537 Improve UI for forgot password button
  src/components/Profile/LoginForm.vue
Labels: good first issue, General Suggestion
