Repository globe-and-citizen/Celebrity-Fanalyzer, pull requests merged in 2024-10, with the labels that each got.

#605 fix:#604 - fixed bux that were spotted while testing with team
  index.html
  public/icons/x.svg
  src/components/Admin/TableEntry.vue
  src/components/Advertiser/AdvertiserTable.vue
  src/components/Posts/Graphs/SharesPie.vue
  src/components/Posts/ShareComponent.vue
  src/components/Posts/ThePost.vue
  src/components/Profile/ProfileTab.vue
  src/pages/CampaignPage.vue
  src/pages/EntryPage.vue
  src/pages/PublicProfilePage.vue
Labels: bug, General Suggestion

#606 fix:#592 - fixed prompt date on search page and on post page
  src/components/Posts/ThePost.vue
  src/components/shared/ItemCard.vue
  src/utils/date.js
Labels: bug, enhancement, General Suggestion

#615 fix:#613 - Advertisement Slug Access Causing App Throttling and Infin…
  src/stores/advertises.js
Labels: bug

#617 fix:#616 - Inaccurate Advertise status for published advertise
  src/components/Advertiser/AdvertiserTable.vue
Labels: bug, General Suggestion

#611 fix:#574 - First comment loading issue
  src/components/Posts/TheComments.vue
Labels: bug, General Suggestion

#622 fix:#618 - implemented feedback tab loader
  index.html
  src/components/Admin/ManageFeedbacks.vue
  src/components/Profile/LoginForm.vue
  src/layouts/MainMenu.vue
  src/stores/feedbacks.js
Labels: enhancement, General Suggestion

#624 fix:#623 - sign-in-error
  src/stores/user.js
Labels: bug, General Suggestion

#612 fix:#609 - fixing bug and check escrow id for entry
  src/components/Admin/EntryCard.vue
  src/components/Admin/PromptCard.vue
Labels: bug, enhancement, General Suggestion

#626 changes concerned strings
  src/components/Admin/FundDepositCard.vue
  src/components/Admin/WalletPaymentCard.vue
  src/components/Advertiser/AdvertiseCard.vue
  src/web3/adCampaignManager.js
  src/web3/transfers.js
Labels: General Suggestion

#631 fix:#627 - Update cost calculation
  src/components/Advertiser/AdvertiserTable.vue
Labels: bug

#629 fix:#628 - Notifications - capitalize first letter + fix grammatical issues
  src/components/Admin/CryptoTransactionDetailCard.vue
  src/components/Admin/EntryCard.vue
  src/components/Admin/FundDepositCard.vue
  src/components/Admin/ManagePromptsEntries.vue
  src/components/Admin/PromptCard.vue
  src/components/Admin/TableEntry.vue
  src/components/Admin/WalletPaymentCard.vue
  src/components/Advertiser/AdvertiserTable.vue
  src/stores/crypto-transactions.js
  src/stores/entries.js
Labels: bug

#610 feat:#557 Implemented native device features camera
  src/components/Admin/EntryCard.vue
  src/components/Admin/PromptCard.vue
  src/components/shared/CameraCapture.vue
  src/utils/media.js
Labels: enhancement, advanced, General Suggestion

#632 fix:#625 - implemented report tab loader
  src/components/Admin/ManageReports.vue
  src/stores/reports.js
Labels: enhancement, General Suggestion

#640 feat:#635 - implemented display no entries message & button
  src/components/shared/TheHeader.vue
  src/pages/PublicProfilePage.vue
Labels: enhancement, General Suggestion

#641 fix:#621 - fixed admin create entry prompt
  src/components/Admin/EntryCard.vue
  src/components/Admin/PromptCard.vue
Labels: bug, General Suggestion

#643 feat:#642 - implement default initials profile pic
  src/pages/PublicProfilePage.vue
Labels: enhancement, General Suggestion

#649 feat:#648 - performance optimizations
  index.html
  package-lock.json
  package.json
  src/App.vue
  src/components/Admin/CryptoTransactionDetailCard.vue
  src/components/Admin/EntryCard.vue
  src/components/Admin/ManageUsers.vue
  src/components/Admin/WalletPaymentCard.vue
  src/components/Advertiser/AdvertiserTable.vue
  src/components/Profile/Web3ModalComponent.vue
  src/components/shared/TheHeader.vue
  src/pages/IndexPage.vue
  src/pages/admin/AdminIndex.vue
  src/stores/advertises.js
  src/stores/clicks.js
  src/stores/comments.js
  src/stores/crypto-transactions.js
  src/stores/entries.js
  src/stores/impressions.js
  src/stores/index.js
  src/stores/likes.js
  src/stores/notifications.js
  src/stores/prompts.js
  src/stores/reports.js
  src/stores/shares.js
  src/stores/user.js
  src/stores/visitors.js
Labels: bug

#644 fix:#576 - fixed comments like & dislike re-render
  src/stores/comments.js
Labels: bug, General Suggestion

#647 fix:#646 - fixed footer tooltip & header title admin panel
  src/layouts/MainMenu.vue
  src/pages/admin/AdminIndex.vue
Labels: bug, good first issue, General Suggestion

#651 fix:#507 - fixed forgot password fails for fake emails
  src/components/Profile/LoginForm.vue
  src/stores/user.js
Labels: bug, General Suggestion
