Repository globe-and-citizen/Celebrity-Fanalyzer, pull requests merged in 2025-02, with the labels that each got.

#657 fix:#656 - improved cypress test
  .github/workflows/cypress.yml
  .nycrc
  cypress.config.js
  package-lock.json
  package.json
  quasar.config.js
  src/components/Admin/EntryCard.vue
  src/components/Admin/ManageErrors.vue
  src/components/Admin/ManageFeedbacks.vue
  src/components/Admin/ManagePromptsEntries.vue
  src/components/Admin/ManageUsers.vue
  src/components/Admin/PromptCard.vue
  src/components/Admin/TableEntry.vue
  src/components/Posts/Graphs/Map/LeafletMap.vue
  src/components/Posts/Graphs/Map/handlingFunctions.js
  src/components/Posts/TheAnthrogram.vue
  src/components/Posts/ThePost.vue
  src/components/Profile/LoginForm.vue
  src/components/Profile/ProfileTab.vue
  src/components/Profile/SettingsTab.vue
  src/components/Profile/SubscriptionsTab.vue
  src/components/date/MonthPicker.vue
  src/components/shared/NotificationBubble.vue
  src/components/shared/TheEntries.vue
  src/components/shared/TheHeader.vue
  src/layouts/MainMenu.vue
  src/pages/EntryPage.vue
  src/pages/admin/AdminIndex.vue
  src/stores/prompts.js
  src/utils/date.js
  test/cypress/e2e/admin-prompt-entry.cy.js
  test/cypress/e2e/admin-user-role.cy.js
  test/cypress/e2e/comment.cy.js
  test/cypress/e2e/entries.cy.js
  test/cypress/e2e/feedbacks.cy.js
  test/cypress/e2e/header-navigation.cy.js
  test/cypress/e2e/home.cy.js
  test/cypress/e2e/login-logout.cy.js
  test/cypress/e2e/manage-errors.cy.js
  test/cypress/e2e/search.cy.js
  test/cypress/e2e/share-prompt.cy.js
  test/cypress/e2e/terms-of-service.cy.js
  test/cypress/e2e/the-anthrogram.cy.js
  test/cypress/e2e/user-profile.cy.js
  test/cypress/support/commands.js
Labels: Type: Enhancement, Type: External, Status: In progress

#697 Fix for Incorrect Social Media URL Redirection (Double URL Issue)
  src/components/Profile/ProfileTab.vue
  src/pages/PublicProfilePage.vue
  test/cypress/e2e/user-profile.cy.js
Labels: Status: Ready for review, Status: Completed

#693 feat:#689 - entry art carousel, clean setup
  package-lock.json
  package.json
  src/components/Admin/EntryCard.vue
  src/components/Admin/ShowcaseCard.vue
  src/components/Admin/TableEntry.vue
  src/components/Posts/ShowcaseArt.vue
  src/components/Posts/ThePost.vue
  src/components/shared/TheEntries.vue
  src/components/shared/TheHeader.vue
  src/pages/EntryPage.vue
  src/pages/IndexPage.vue
  src/pages/admin/AdminIndex.vue
  src/stores/entries.js
  src/stores/storage.js
  src/utils/imageConvertor.js
  test/cypress/e2e/admin-prompt-entry.cy.js
  test/cypress/e2e/login-logout.cy.js
  test/cypress/fixtures/assets/cypress.jpg
Labels: Status: Ready for review
